version: "3.9"
services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [redis]
  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=INFO --concurrency=${MAX_CONCURRENCY:-4}
    env_file: .env
    depends_on: [redis]
  redis:
    image: redis:7
    ports: ["6379:6379"]